Repository argonne-lcf/user-guides, pull requests merged in 2025-06, with the labels that each got.

#911 Fix syntax error
  docs/aurora/getting-started-on-aurora.md
Labels: content

#913 Update allocation-management.md
  docs/account-project-management/allocation-management/allocation-management.md
Labels: content

#907 Added three new pages for tokens, removed the old tokens page, and up…
  docs/account-project-management/MyALCF.md
  docs/account-project-management/accounts-and-access/accounts-and-access-faqs.md
  docs/account-project-management/accounts-and-access/alcf-passcode-tokens.md
  docs/account-project-management/accounts-and-access/logging-in-with-tokens.md
  docs/account-project-management/accounts-and-access/obtaining-a-token.md
  docs/account-project-management/accounts-and-access/troubleshooting-tokens.md
  docs/services/jupyter-hub.md
  mkdocs.yml
Labels: web rendering, content, organization

#915 fix: dropdown on hover
  docs/stylesheets/alcf-extra.css
Labels: web rendering

#917 Minor changes for updated sambaflow. Also, provide instructions for d…
  docs/ai-testbed/sambanova/example-multi-node-programs.md
  docs/ai-testbed/sambanova/example-programs.md
  docs/ai-testbed/sambanova/files/Gpt1.5B_compile.sh
Labels: content

#920 Create standalone HTML template + file for AuroraBugTracking
  docs/aurora/bugs-table.md
  docs/aurora/known-issues.md
  docs/javascripts/tablesort.js
  mkdocs.yml
  overrides/main.html
  overrides/standalone.html
Labels: web rendering, content, external sites, style

#921 Fix table sorting ascending/descending in standalone table
  docs/javascripts/tablesort.js
  mkdocs.yml
Labels: web rendering

#918 Updated Tokens Pages with Anchor Links
  docs/account-project-management/accounts-and-access/logging-in-with-tokens.md
  docs/account-project-management/accounts-and-access/obtaining-a-token.md
  docs/account-project-management/accounts-and-access/troubleshooting-tokens.md
Labels: content

#927 Update Aurora apptainer docs
  docs/aurora/containers/containers.md
Labels: content
