Repository argonne-lcf/user-guides, pull requests merged in 2025-04, with the labels that each got.

#811 Update header dropdown links to user-guides URLs
  includes/validate-inbound-URLs.txt
  mkdocs.yml
  overrides/partials/header.html
  requirements.txt
Labels: maintenance, external sites, organization

#828 Rename contacting-support/ ---> support/
  .github/ISSUE_TEMPLATE/config.yml
  docs/CODEOWNERS
  docs/account-project-management/accounts-and-access/accounts-and-access-faqs.md
  docs/account-project-management/allocation-management/index.md
  docs/account-project-management/project-management/team-management.md
  docs/ai-testbed/groq/job-queuing-and-submission.md
  docs/aurora/getting-started-on-aurora.md
  docs/aurora/known-issues.md
  docs/aurora/services/gitlab-ci.md
  docs/polaris/applications-and-libraries/applications/nekrs.md
  docs/polaris/data-science/python.md
  docs/polaris/system-updates.md
  docs/polaris/workflows/libensemble.md
  docs/support/alcf-users-slack.md
  docs/support/docs-issues.md
  docs/support/index.md
  docs/support/office-hours.md
  docs/support/software-requests.md
  docs/support/technical-support.md
  includes/validate-inbound-URLs.txt
  mkdocs.yml
Labels: organization

#826 Reorganize MIG mode, MPS, and Polaris gpu content.
  docs/account-project-management/project-management/starting-alcf-award.md
  docs/polaris/compiling-and-linking/index.md
  docs/polaris/compiling-and-linking/polaris-example-program-makefile.md
  docs/polaris/getting-started.md
  docs/polaris/running-jobs/index.md
  docs/polaris/running-jobs/using-gpus.md
  docs/polaris/workflows/mig-compute.md
  docs/running-jobs/example-job-scripts.md
  docs/services/jupyter-hub.md
  mkdocs.yml
Labels: organization

#832 Update known-issues.md
  docs/aurora/known-issues.md
Labels: content, external sites

#831 Update index.md
  docs/data-management/filesystem-and-storage/index.md
  docs/polaris/running-jobs/using-gpus.md
Labels: content

#833 Update 3x submodules every day, early AM
  .github/workflows/update-submodules.yml
  docs/aurora/known-issues.md
Labels: mkdocs enhancement, external sites

#834 Cerebras remove old cred info
  docs/ai-testbed/cerebras/job-queuing-and-submission.md
  docs/ai-testbed/cerebras/miscellaneous.md
Labels: content

#835 Use "GPU-aware MPI" terminology.
  docs/polaris/compiling-and-linking/index.md
  docs/polaris/running-jobs/using-gpus.md
  docs/running-jobs/example-job-scripts.md
Labels: content

#839 Update daos-overview.md with info about libfabric endpoint creation e…
  docs/aurora/data-management/daos/daos-overview.md
Labels: content

#841 Aurora: scaling out of shared filesystems
  docs/aurora/known-issues.md
Labels: content

#837 chore: Fix typo
  docs/aurora/data-management/daos/daos-overview.md
Labels: content

#840 Update vllm.md
  docs/aurora/data-science/inference/vllm.md
Labels: content

#842 Clarify PR type differences
  .github/pull_request_template.md
Labels: maintenance

#843 Fix nightly GH Action for updating submodules
  .github/workflows/update-submodules.yml
Labels: maintenance, external sites

#852 docs: Update `aurora/data-management/daos/daos-overview.md`
  docs/aurora/data-management/daos/daos-overview.md
Labels: content

#855 clarify UAN proxy status
  docs/aurora/getting-started-on-aurora.md
Labels: content
