Repository argonne-lcf/user-guides, pull requests merged in 2025-03, with the labels that each got.

#780 Update running-jobs-aurora.md
  docs/aurora/running-jobs-aurora.md
Labels: content

#799 Modify GitHub Action to validate important external, inbound URLs matching source .md paths
  .github/workflows/mkdocs-build.yml
  .gitignore
  Makefile
  README.md
  includes/validate-inbound-URLs.txt
  mkdocs.yml
  scripts/generate_inbound_links.py
  scripts/validate_inbound_links.py
Labels: maintenance

#801 Update user-authentication-policy.md
  docs/policies/accounts/user-authentication-policy.md
Labels: content

#804 Add CODEOWNERS file, Issue template forms, PR template
  .github/ISSUE_TEMPLATE/blank.yml
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/task.yml
  .github/pull_request_template.md
  docs/CODEOWNERS
  docs/aurora/compiling-and-linking/aurora-example-program-makefile.md
Labels: maintenance, organization

#805 Update running-jobs-aurora.md for references to gpu_tile_compact.sh
  docs/aurora/running-jobs-aurora.md
Labels: content

#806 Fix Issue template chooser config
  .github/ISSUE_TEMPLATE/config.yml
  .github/pull_request_template.md
  overrides/partials/toc.html
Labels: maintenance

#807 Fix issue template chooser config, part deux
  .github/ISSUE_TEMPLATE/1-task.yml
  .github/ISSUE_TEMPLATE/2-bug_report.yml
  .github/ISSUE_TEMPLATE/3-feature_request.yml
  .github/ISSUE_TEMPLATE/4-blank.yml
  .github/ISSUE_TEMPLATE/config.yml
  docs/account-project-management/allocation-management/index.md
Labels: maintenance

#808 Formatting issue
  .github/ISSUE_TEMPLATE/config.yml
Labels: maintenance

#809 Fix YAML indentation
  docs/polaris/data-science/applications/gpt-neox.md
  mkdocs.yml
Labels: maintenance, style

#785 Paraview on Aurora
  docs/aurora/visualization/images/ParaviewChooseServerConfig.png
  docs/aurora/visualization/images/ParaviewConnectMenu.png
  docs/aurora/visualization/images/ParaviewConnected.png
  docs/aurora/visualization/images/ParaviewConnectionOptions.png
  docs/aurora/visualization/images/ParaviewWaitForServer.png
  docs/aurora/visualization/images/choose-server.png
  docs/aurora/visualization/images/connect-icon.png
  docs/aurora/visualization/images/edit-server.png
  docs/aurora/visualization/index.md
  docs/aurora/visualization/paraview-manual-launch.md
  docs/aurora/visualization/paraview.md
  docs/aurora/visualization/serverfiles/aurora.pvsc
  docs/aurora/visualization/serverfiles/windowsToAurora.pvsc
  mkdocs.yml
Labels: content

#813 Updating codee.md to add issue from Victor
  docs/aurora/debugging/codee.md
Labels: content

#814 fix: Update default fg color in dark theme
  docs/stylesheets/alcf-extra.css
Labels: style

#815 fix: Update default fg color in dark theme (take 2)
  docs/stylesheets/alcf-extra.css
Labels: style

#817 quick add extra info about gitlab runners proxies and crux
  docs/services/gitlab-ci.md
Labels: content

#816 [Aurora] Fix MPICH GPU-aware env variable
  docs/aurora/running-jobs-aurora.md
Labels: content

#819 Update known-issues.md to include possibility of GPU buffer issue
  docs/aurora/known-issues.md
Labels: content

#824 Test CODEOWNERS syntax flexibility; narrowly tailor workflows/ ownership
  docs/CODEOWNERS
Labels: maintenance
